# Clase 11
### Webscrapping

In [5]:
import seaborn as sns

import seaborn.objects as so
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

En este trabajo exploraremos la base de datos `Sleep_Efficiency_Cleaning.csv`. Es una base descargada de kaggle.com generada a partir de información sobre los hábitos de sueño de distintas personas. La base está levemente modificada para los ejercicios de este trabajo. Las variables incluidas son:

- **ID:** identificación de participante
- **Age:** edad
- **Gender:** que designa al género de cada persona
- **Bedtime:** que tiene la hora a la que se va a dormir la persona
- **Wakeup time:** que tiene la hora a la que se despiertan las personas
- **Sleep.duration:**  que nos dice cuánto tiempo pasa cada persona durmiendo
- **Sleep.efficiency:** que nos dice cuanto del tiempo que pasan laa persona en la cama, efectivamente duermen.
- **REM sleep percentage:**  que tiene la proporción de sueño REM de la persona
- **Deep sleep percentage:**  que tiene la proporción de sueño profundo de la persona
- **Light sleep percentage:**  que tiene la proporción de sueño liviano de la persona
- **Awakenings:** que tiene la cantidad de veces que la persona se despierta a la noche
- **Caffeine consumption:** que nos dice la cantidad de cafeina que consume la persona
- **Alcohol consumption:** que nos dice la cantidad de alcohol que consume la persona
- **Smoking.status:** que nos dice si la persona es o no es fumadora
- **Excersice frequency:** que nos dice cuán frecuentemente hace ejercicio la persona

In [61]:
datos = pd.read_csv("../Descargas/Sleep_efficiency_cleaning.csv")
datos

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

#### 1. Con lo que sabemos hasta ahora, tomemonos 10 minutos para chusmear los datos

¿Les parece que podría haber cosas para limpiar en los datos? ¿Por qué?

### 2. Limpieza de los datos

Nos interesará realizar algunas acciones de limpieza de datos:
- Filtrar datos
- Renombrar variables
- Eliminar datos faltantes
- Eliminar duplicados
- Filtrar datos

#### 2.a. Filtrado

In [23]:
masDeSeisHorasYAdultos = datos[(datos["Sleep duration"] >= 6.0) & (datos["Age"] >= 17)]
masDeSeisHorasYAdultos

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

### 2.b. Renombrar variables con diccionarios

Como vimos, nuestra base de datos tiene nombres de variables en ingles. Pero como nosotros somos más argentinos que usar ojotas con medias, vamos a pasarlo al castellano.

Para eso, nos van a servir mucho los **diccionarios**, que se utilizan para almacenar valores de datos en pares clave:valor.

Un diccionario es una colección ordenada, modificable y que no permite duplicados.

Yo podría generar este diccionario llamado dict

In [11]:
# Ejemplo
dict = { "hola" : "Expresión de saludo utilizada entre dos o más personas de trato familiar", "cinco" : 5, "dias" : ["lunes", "martes", "miercoles"]}

Si le pregunto que significa "hola", me dirá:

In [12]:
dict["hola"]

'Expresión de saludo utilizada entre dos o más personas de trato familiar'

Para lo que nos interesa a nosotros, podríamos tener lo siguiente:

In [37]:
nombres = {
  "ID": "ID",
  "Age": "Edad",
  "Gender": "Género",
  "Bedtime": "Hora dormir",
  "Wakeup time": "Hora despertar",
  "Sleep duration": "Duracion sueño",
  "Sleep efficiency": "Eficiencia sueño",
  "REM sleep percentage": "Porcentaje sueño REM",
  "Deep sleep percentage": "Porcentaje sueño profundo",
  "Light sleep percentage": "Porcentaje sueño liviano",
  "Awakenings": "Despertares",
  "Caffeine consumption": "Consumo cafeina",
  "Alcohol consumption": "Consumo alcohol",
  "Smoking status": "Fumador",
  "Exercise frequency": "Frecuencia ejercicio"
}

Para cambiar los nombres deberíamos usar rename() ¿Cómo lo usarian?

Pueden chusmear la ayuda

In [39]:
datos = datos.rename(columns = nombres)
datos

,ID,Edad,Género,Hora dormir,Hora despertar,Duracion suenio,Eficiencia suenio,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Despertares,Consumo cafeina,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [45]:
datos_upper = datos.rename(columns= str.upper)
datos_upper

,ID,EDAD,GÉNERO,HORA DORMIR,HORA DESPERTAR,DURACION SUENIO,EFICIENCIA SUENIO,PORCENTAJE SUENIO REM,PORCENTAJE SUENIO PROFUNDO,PORCENTAJE SUENIO LIVIANO,DESPERTARES,CONSUMO CAFEINA,CONSUMO ALCOHOL,FUMADOR,FRECUENCIA EJERCICIO
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [13]:
help(pd.DataFrame.rename)

Help on function rename in module pandas.core.frame:

rename(self, mapper: 'Renamer | None' = None, *, index: 'Renamer | None' = None, columns: 'Renamer | None' = None, axis: 'Axis | None' = None, copy: 'bool | None' = None, inplace: 'bool' = False, level: 'Level' = None, errors: 'IgnoreRaise' = 'ignore') -> 'DataFrame | None'
    Rename columns or index labels.

    Function / dict values must be unique (1-to-1). Labels not contained in
    a dict / Series will be left as-is. Extra labels listed don't throw an
    error.

    See the :ref:`user guide <basics.rename>` for more.

    Parameters
    ----------
    mapper : dict-like or function
        Dict-like or function transformations to apply to
        that axis' values. Use either ``mapper`` and ``axis`` to
        specify the axis to target with ``mapper``, or ``index`` and
        ``columns``.
    index : dict-like or function
        Alternative to specifying axis (``mapper, axis=0``
        is equivalent to ``index=mapper``).
    columns : dict-like or function
        Alternative to specifying axis (``mapper, axis=1``
        is equivalent to ``columns=mapper``).
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis to target with ``mapper``. Can be either the axis name
        ('index', 'columns') or number (0, 1). The default is 'index'.
    copy : bool, default True
        Also copy underlying data.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
        If True then value of copy is ignored.
    level : int or level name, default None
        In case of a MultiIndex, only rename labels in the specified
        level.
    errors : {'ignore', 'raise'}, default 'ignore'
        If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
        or `columns` contains labels that are not present in the Index
        being transformed.
        If 'ignore', existing keys will be renamed and extra keys will be
        ignored.

    Returns
    -------
    DataFrame or None
        DataFrame with the renamed axis labels or None if ``inplace=True``.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis and
        "errors='raise'".

    See Also
    --------
    DataFrame.rename_axis : Set the name of the axis.

    Examples
    --------
    ``DataFrame.rename`` supports two calling conventions

    * ``(index=index_mapper, columns=columns_mapper, ...)``
    * ``(mapper, axis={'index', 'columns'}, ...)``

    We *highly* recommend using keyword arguments to clarify your
    intent.

    Rename columns using a mapping:

    >>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
    >>> df.rename(columns={"A": "a", "B": "c"})
       a  c
    0  1  4
    1  2  5
    2  3  6

    Rename index using a mapping:

    >>> df.rename(index={0: "x", 1: "y", 2: "z"})
       A  B
    x  1  4
    y  2  5
    z  3  6

    Cast index labels to a different type:

    >>> df.index
    RangeIndex(start=0, stop=3, step=1)
    >>> df.rename(index=str).index
    Index(['0', '1', '2'], dtype='object')

    >>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
    Traceback (most recent call last):
    KeyError: ['C'] not found in axis

    Using axis-style parameters:

    >>> df.rename(str.lower, axis='columns')
       a  b
    0  1  4
    1  2  5
    2  3  6

    >>> df.rename({1: 2, 2: 4}, axis='index')
       A  B
    0  1  4
    2  2  5
    4  3  6

#### 2. c. Eliminar valores faltantes

¿Qué significa un valor faltante?

Los datos faltantes son algo típico de cualquier pipeline de análisis de datos. En general los paquetes estadísticos (pandas, dplyr, etc) tratan de facilitar el manejo de estos tipos de datos. En Pandas, se utiliza la expresión NaN (Not a number) o NA que viene del mundo R (Not available)

Para poder acceder a los datos faltantes, podemos utilizar la función isna() 

¿Cómo la usamos? ¿Qué nos devuelve?

In [48]:
datos.isna()

,ID,Edad,Género,Hora dormir,Hora despertar,Duracion suenio,Eficiencia suenio,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Despertares,Consumo cafeina,Consumo alcohol,Fumador,Frecuencia ejercicio
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
458,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
459,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
460,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
461,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [47]:
datos.isna().sum()

ID                             0
Edad                           0
Género                         0
Hora dormir                    0
Hora despertar                 0
Duracion suenio                0
Eficiencia suenio              0
Porcentaje suenio REM          0
Porcentaje suenio profundo     0
Porcentaje suenio liviano      0
Despertares                   20
Consumo cafeina               25
Consumo alcohol               15
Fumador                        0
Frecuencia ejercicio           6
dtype: int64

In [51]:
datosWONa = datos.dropna()
datosWONa

,ID,Edad,Género,Hora dormir,Hora despertar,Duracion suenio,Eficiencia suenio,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Despertares,Consumo cafeina,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [63]:
datosDropNa15 = datos.dropna(thresh = 15)
datosDropNa15

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [67]:
datosWOSmoking = datos.drop(columns = "Smoking status")
datosWOSmoking

datosDropNa15WOCaffandAlch = datos.drop(columns = ["Caffeine consumption", "Alcohol consumption"])
datosDropNa15WOCaffandAlch

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,Yes,3.0

### 2.d. Eliminar datos duplicados

En muchos casos puede suceder que haya datos duplicados en nuestro dataset. ¿Se les ocurren ejemplos?

Para identificarlos, podemos usar duplicated(). ¿Qué está haciendo esta función?

In [70]:
#datos.duplicated() no sirve mucho, nos da True or False
datos.drop_duplicates()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3.0,0.0,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1.0,50.0,0.0,No,1.0
453,40,58,Female,2021-03-26 02:00:00,2021-03-26 09:00:00,7.0,0.63,22,23,55,3.0,50.0,3.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [71]:
datos["ID"].duplicated().sum()

16

In [72]:
datos.drop_duplicates(subset = "ID", keep = "last")

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

### 2.e. Resetear el index

Una vez que eliminamos filas por el motivo que sea, nos van a quedar medio raros index. Veamos como nos quedó datos2

In [74]:
datos.reset_index()
datos.reset_index(drop=True) #elimina la columna que indica los index antes de cambiarlos

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

### 3. Encadenar métodos

Esta forma de ir modificando un dataset no es muy práctica.

Por ejemplo si ejecutamos varias veces el mismo comando sin renombrar los datos, obtendremos cada vez algo distinto.

Si estamos creando un dataframe nuevo cada vez que hacemos algo, vamos a tener la memoria llena de objetos prácticamente iguales

Una solución es encadenar métodos para hacer el código más legible y fácil de reusar. Y más eficiente también.

Cada función genera un nuevo dataframe. Asi que siempre tengo que usar funciones que me generen un dataframe.

In [82]:
datos[(datos["Age"] >= 17) & (datos["Sleep duration"] >= 6)].drop(columns = ["Caffeine consumption", "Alcohol consumption"])
.dropna()
.drop_duplicates(subset = "ID", keep = "last")
.Alcohol consumption

SyntaxError: invalid syntax (1762381146.py, line 2)

#### Extra: pipes
Una cadena de operaciones encadenadas suele llamarse un "pipe" (tubería). 

Por ejemplo, en R podemos hacer pipes en un DataFrame con %>%:

`first(x) %>% second(x) %>% third(x)`

En Python podemos encadenar métodos directamente poniendo uno a continuación del otro, por lo tanto en general no necesitamos un comando especial para pipes. 

Igualmente, los DataFrames de Pandas también tienen un método `pipe()` para encadenar funciones aplicadas al DataFrame que puede resultar útil.